#!/usr/bin/env python3
"""Render query results as a self-contained HTML report page.

Input (JSON on stdin or --input file):
{
  "title": "Leads this week",
  "columns": [{"field": "company", "title": "Company"}, ...],
  "rows": [{"company": "Acme", ...}, ...],
  "chart": {"type": "bar"|"pie", "title": "...",
            "labels": [...], "values": [...]},   // optional
  "note": "footer note"                           // optional
}

Output: writes the HTML file and prints {"ok": true, "file": path}.
Uses Tabulator (MIT) for the interactive table and Apache ECharts
(Apache-2.0) for the optional chart, loaded from a CDN (configurable below
for China deployments).
"""
import argparse
import html
import json
import sys
import tempfile

# Swap for a China-friendly mirror if needed, e.g.
# https://registry.npmmirror.com/<pkg>/<ver>/files/dist/...
CDN_TABULATOR_JS = "https://cdn.jsdelivr.net/npm/tabulator-tables@6.3.0/dist/js/tabulator.min.js"
CDN_TABULATOR_CSS = "https://cdn.jsdelivr.net/npm/tabulator-tables@6.3.0/dist/css/tabulator_simple.min.css"
CDN_ECHARTS_JS = "https://cdn.jsdelivr.net/npm/echarts@5.6.0/dist/echarts.min.js"

PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<link rel="stylesheet" href="{tab_css}">
<style>
:root {{ --ink:#1e242c; --muted:#5a6470; --ground:#f5f6f8; --surface:#fff;
        --line:#e2e6eb; }}
@media (prefers-color-scheme: dark) {{
  :root {{ --ink:#e5e9ed; --muted:#98a2ad; --ground:#13161b;
          --surface:#1b2129; --line:#2a313b; }}
  .tabulator, .tabulator .tabulator-header, .tabulator .tabulator-header
  .tabulator-col, .tabulator-row {{ background: var(--surface);
    color: var(--ink); border-color: var(--line); }}
  .tabulator-row.tabulator-row-even {{ background: var(--ground); }}
}}
body {{ margin:0; background:var(--ground); color:var(--ink);
  font:16px/1.7 -apple-system, "PingFang SC", "Microsoft YaHei",
  system-ui, sans-serif; }}
.wrap {{ max-width: 62rem; margin: 0 auto; padding: 2rem 1rem 3rem; }}
h1 {{ font-size: 1.5rem; margin: 0 0 .3rem; }}
.meta {{ color: var(--muted); font-size: .82rem; margin-bottom: 1.2rem; }}
#chart {{ width: 100%; height: 320px; margin: 1.2rem 0;
  background: var(--surface); border: 1px solid var(--line);
  border-radius: 8px; }}
#table {{ border: 1px solid var(--line); border-radius: 8px; }}
.note {{ color: var(--muted); font-size: .85rem; margin-top: 1rem; }}
.expiry {{ display:inline-block; margin-top:1.4rem; color:var(--muted);
  font-size:.78rem; border:1px dashed var(--line); border-radius:99px;
  padding:.1rem .8rem; }}
</style>
</head>
<body>
<div class="wrap">
  <h1>{title}</h1>
  <div class="meta">{row_count} rows · generated by your agent</div>
  {chart_div}
  <div id="table"></div>
  {note_html}
  <span class="expiry">⏳ This page is temporary and will stop working
  shortly after it was shared.</span>
</div>
<script src="{tab_js}"></script>
{echarts_tag}
<script>
const DATA = {data_json};
new Tabulator("#table", {{
  data: DATA.rows,
  columns: DATA.columns,
  layout: "fitDataStretch",
  pagination: DATA.rows.length > 50,
  paginationSize: 50,
}});
{chart_script}
</script>
</body>
</html>
"""

CHART_SCRIPT = """
const chart = echarts.init(document.getElementById('chart'), null,
                           {renderer: 'canvas'});
const dark = window.matchMedia('(prefers-color-scheme: dark)').matches;
const C = DATA.chart;
chart.setOption({
  title: {text: C.title || '', textStyle: {fontSize: 14,
          color: dark ? '#e5e9ed' : '#1e242c'}},
  tooltip: {},
  ...(C.type === 'pie' ? {
    series: [{type: 'pie', radius: ['35%', '65%'],
      data: C.labels.map((l, i) => ({name: l, value: C.values[i]}))}]
  } : {
    xAxis: {type: 'category', data: C.labels,
            axisLabel: {color: dark ? '#98a2ad' : '#5a6470'}},
    yAxis: {type: 'value',
            axisLabel: {color: dark ? '#98a2ad' : '#5a6470'}},
    series: [{type: 'bar', data: C.values, itemStyle: {color: '#0e7490'}}]
  })
});
addEventListener('resize', () => chart.resize());
"""


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--input", help="JSON file (default: stdin)")
    p.add_argument("--output", help="HTML output path (default: temp file)")
    a = p.parse_args()

    raw = open(a.input, encoding="utf-8").read() if a.input else sys.stdin.read()
    spec = json.loads(raw)
    if not spec.get("columns") or "rows" not in spec:
        print(json.dumps({"ok": False,
                          "error": "spec needs 'columns' and 'rows'"}))
        sys.exit(1)

    has_chart = bool(spec.get("chart"))
    page = PAGE.format(
        title=html.escape(spec.get("title", "Report")),
        row_count=len(spec["rows"]),
        tab_css=CDN_TABULATOR_CSS,
        tab_js=CDN_TABULATOR_JS,
        echarts_tag=(f'<script src="{CDN_ECHARTS_JS}"></script>'
                     if has_chart else ""),
        chart_div='<div id="chart"></div>' if has_chart else "",
        chart_script=CHART_SCRIPT if has_chart else "",
        note_html=(f'<div class="note">{html.escape(spec["note"])}</div>'
                   if spec.get("note") else ""),
        data_json=json.dumps(spec, ensure_ascii=False),
    )
    out = a.output or tempfile.mkstemp(suffix=".html", prefix="richview-")[1]
    with open(out, "w", encoding="utf-8") as f:
        f.write(page)
    print(json.dumps({"ok": True, "file": out, "rows": len(spec["rows"]),
                      "chart": has_chart}))


if __name__ == "__main__":
    main()
