#!/usr/bin/env python3
"""Render INDEX files from the DB (generated files — never hand-edit)."""
import bizlib


def render_leads(con):
    rows = con.execute("SELECT * FROM leads ORDER BY updated_at DESC").fetchall()
    lines = [
        "# Leads Index",
        "",
        "> Generated by render_index.py — do not edit by hand.",
        "",
        "| ID | Company | Contact | Stage | Value (CNY) | Next due | Updated |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        value = f"{r['value_cny']:,}" if r["value_cny"] is not None else "—"
        lines.append(
            f"| {r['id']} | {r['company']} | {r['contact'] or '—'} | {r['stage']} "
            f"| {value} | {r['next_due'] or '—'} | {r['updated_at'][:10]} |")
    path = bizlib.BIZ_HOME / "leads" / "INDEX.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(path)


def main():
    con = bizlib.connect()
    path = render_leads(con)
    con.close()
    bizlib.ok({"rendered": [path]})


if __name__ == "__main__":
    main()
